# Stage 1: Build using Maven
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Run the app with a lightweight JDK
FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app

# Copy the built JAR file from the previous stage
COPY --from=build /app/target/patient-service-0.0.1-SNAPSHOT.jar app.jar

# Expose the Spring Boot default port
EXPOSE 4000

# Start the application
ENTRYPOINT ["java", "-jar", "app.jar"]
